service: github-actions-badge

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-west-2

package:
  exclude:
    - coverage/
    - server.js
    - test/

functions:
  badge:
    handler: handler.handle
    events:
      - http:
          path: badge/{owner}/{repo}
          method: get
      - http:
          path: results/{owner}/{repo}
          method: get
