service: github-actions-badge

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'us-west-2'}

package:
  exclude:
    - server.js

functions:
  badge:
    handler: handler.handle
    environment:
      GITHUB_TOKEN: ${file(.env.yml):GITHUB_TOKEN}
    events:
      - http:
          path: badge/{owner}/{repo}
          method: get
      - http:
          path: results/{owner}/{repo}
          method: get
